language: python

python:
  - "2.7"

cache: pip

env:
  global:
    - TOXENV=py27
    - DJANGO_SETTINGS_MODULE=cfgov.settings.test
    - DJANGO_STAGING_HOSTNAME=content.localhost
    - COVERALLS_PARALLEL=true

  matrix:
    - RUNTEST=frontend
    - RUNTEST=backend

script:
  - ./run_travis.sh

notifications:
  webhooks: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN

