version: "2"

services:
    base:
        build: docker/base
        image: cfgov_base
    gulp:
        build:
            context: .
            dockerfile: docker/gulp/Dockerfile
        volumes:
            - .:/src
        depends_on:
            - base
    django:
        build:
            context: .
            dockerfile: docker/django/Dockerfile
        volumes:
            - .:/src
        depends_on:
            - base
